# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-09-22 10:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='map',
            options={'verbose_name': 'Карта', 'verbose_name_plural': 'Карты'},
        ),
        migrations.AlterField(
            model_name='map',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название карты'),
        ),
    ]
