# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-09-21 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gamer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, default=False, max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, default=False, max_length=50, verbose_name='Last Name')),
                ('is_captain', models.BooleanField(default=False, verbose_name='Is he a captain?')),
                ('phone_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Phone number')),
            ],
        ),
    ]
