# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-09-21 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamer',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='gamer',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Last Name'),
        ),
    ]
