# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-09-22 10:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamers', '0002_auto_20170921_1037'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gamer',
            options={'verbose_name': 'Игрок', 'verbose_name_plural': 'Игроки'},
        ),
        migrations.AlterField(
            model_name='gamer',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='gamer',
            name='is_captain',
            field=models.BooleanField(default=False, verbose_name='Капитан'),
        ),
        migrations.AlterField(
            model_name='gamer',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='gamer',
            name='phone_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Номер телефона'),
        ),
    ]
