# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-09-15 12:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='user',
        ),
        migrations.RemoveField(
            model_name='group',
            name='team',
        ),
        migrations.AddField(
            model_name='group',
            name='team',
            field=models.ManyToManyField(to='teams.Team'),
        ),
    ]
