# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-09-21 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamers', '0001_initial'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='user',
        ),
        migrations.AddField(
            model_name='team',
            name='gamers',
            field=models.ManyToManyField(to='gamers.Gamer'),
        ),
    ]
