# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-09-22 10:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_auto_20170921_1035'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': 'Команда', 'verbose_name_plural': 'Команды'},
        ),
        migrations.AlterField(
            model_name='team',
            name='gamers',
            field=models.ManyToManyField(to='gamers.Gamer', verbose_name='Игроки'),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название команды'),
        ),
    ]
