# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-09-24 16:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('widgets', '0003_auto_20170924_0545'),
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('status', model_utils.fields.StatusField(choices=[('Created', 'Created'), ('Scheduled', 'Scheduled'), ('Called', 'Called')], default='Created', max_length=100, no_check_for_status=True, verbose_name='Status')),
                ('subject', models.CharField(max_length=50)),
                ('text', models.CharField(max_length=500)),
                ('file', models.FileField(upload_to='')),
                ('status_changed', model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status')),
                ('scheduled_at', model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', verbose_name='Call scheduled at', when=set(['Sent']))),
                ('called_at', model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='called', verbose_name='Called at', when=set(['Called']))),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmailMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('status', model_utils.fields.StatusField(choices=[('Created', 'Created'), ('Scheduled', 'Scheduled'), ('Sent', 'Sent'), ('Opened', 'Opened'), ('Clicked', 'Clicked')], default='Created', max_length=100, no_check_for_status=True, verbose_name='Status')),
                ('subject', models.CharField(max_length=50, null=True)),
                ('text', models.CharField(max_length=500, null=True)),
                ('html', models.CharField(max_length=1000, null=True)),
                ('status_changed', model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status')),
                ('scheduled_at', model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', verbose_name='Email scheduled at', when=set(['Sent']))),
                ('sent_at', model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', verbose_name='Email sent at', when=set(['Scheduled']))),
                ('opened_at', model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', verbose_name='Email opened at', when=set(['Opened']))),
                ('clicked_at', model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', verbose_name='Email clicked at', when=set(['Clicked']))),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=50, null=True)),
                ('src', models.CharField(max_length=500, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('sending_frequency', model_utils.fields.StatusField(choices=[('One time', 'One time'), ('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Yearly', 'Yearly')], default='One time', max_length=100, no_check_for_status=True, verbose_name='Frequency of sending')),
                ('datetime', models.DateTimeField(null=True)),
                ('complete', models.BooleanField(default=False, verbose_name='Complete')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SMS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('status', model_utils.fields.StatusField(choices=[('Created', 'Created'), ('Scheduled', 'Scheduled'), ('Sent', 'Sent')], default='Created', max_length=100, no_check_for_status=True, verbose_name='Status')),
                ('subject', models.CharField(max_length=50, null=True)),
                ('text', models.CharField(max_length=500, null=True)),
                ('status_changed', model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status')),
                ('scheduled_at', model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', verbose_name='SMS sheduled at', when=set(['Scheduled']))),
                ('sent_at', model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', verbose_name='SMS sent at', when=set(['Sent']))),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TelegramMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('status', model_utils.fields.StatusField(choices=[('Created', 'Created'), ('Scheduled', 'Scheduled'), ('Sent', 'Sent')], default='Created', max_length=100, no_check_for_status=True, verbose_name='Status')),
                ('message', models.CharField(max_length=500, null=True)),
                ('status_changed', model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status')),
                ('scheduled_at', model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', verbose_name='SMS sheduled at', when=set(['Scheduled']))),
                ('sent_at', model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', verbose_name='SMS sent at', when=set(['Sent']))),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='widget',
            old_name='site',
            new_name='website',
        ),
        migrations.RemoveField(
            model_name='leed',
            name='name',
        ),
        migrations.AddField(
            model_name='leed',
            name='first_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='leed',
            name='last_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='leed',
            name='referal',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='leed',
            name='telegram',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='leed',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='widget',
            name='button_color',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='widget',
            name='button_text',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='widget',
            name='competitions',
            field=models.CharField(choices=[('random', 'Random'), ('leeds', 'Leeds')], default='random', max_length=20),
        ),
        migrations.AddField(
            model_name='widget',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='widget',
            name='offer',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='widget',
            name='steps',
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='widget',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='leed',
            name='email',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='leed',
            name='phone_number',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='widget',
            name='status',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='stoped', max_length=20, no_check_for_status=True),
        ),
        migrations.AddField(
            model_name='telegrammessage',
            name='leed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='widgets.Leed'),
        ),
        migrations.AddField(
            model_name='telegrammessage',
            name='widget',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='widgets.Widget'),
        ),
        migrations.AddField(
            model_name='sms',
            name='leed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='widgets.Leed'),
        ),
        migrations.AddField(
            model_name='sms',
            name='widget',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='widgets.Widget'),
        ),
        migrations.AddField(
            model_name='report',
            name='widget',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='widgets.Widget'),
        ),
        migrations.AddField(
            model_name='link',
            name='widget',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='widgets.Widget'),
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='leed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='widgets.Leed'),
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='widget',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='widgets.Widget'),
        ),
        migrations.AddField(
            model_name='call',
            name='leed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='widgets.Leed'),
        ),
        migrations.AddField(
            model_name='call',
            name='widget',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='widgets.Widget'),
        ),
    ]
