# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-09-25 08:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widgets', '0004_auto_20170924_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='widget',
            name='text',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
