# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-09-25 18:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widgets', '0005_widget_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='widget',
            name='token',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
