# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-31 19:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('widgets', '0011_auto_20171031_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='widget',
            name='button_color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='widget',
            name='button_text',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='widget',
            name='competition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='widgets.Competition'),
        ),
        migrations.AlterField(
            model_name='widget',
            name='competition_type',
            field=models.CharField(blank=True, choices=[('random', 'Random'), ('leeds', 'Leeds')], default='random', max_length=20),
        ),
        migrations.AlterField(
            model_name='widget',
            name='date_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='widget',
            name='date_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='widget',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='widget',
            name='offer',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='widget',
            name='status',
            field=model_utils.fields.StatusField(blank=True, choices=[(0, 'dummy')], default='stoped', max_length=20, no_check_for_status=True),
        ),
        migrations.AlterField(
            model_name='widget',
            name='steps',
            field=models.PositiveSmallIntegerField(blank=True, default=3),
        ),
        migrations.AlterField(
            model_name='widget',
            name='text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='widget',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='widget',
            name='token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='widget',
            name='website',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='widgets.Website'),
        ),
    ]
