# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-09-15 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_captain',
            field=models.BooleanField(default=False, verbose_name='Is he a captain?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=255, verbose_name='Phone number'),
        ),
    ]
