# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-09-15 11:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20170915_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_captain',
            field=models.BooleanField(default=False, verbose_name='Is he a captain?'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Phone number'),
        ),
    ]
