# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-09-21 10:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20170915_1134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_captain',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
    ]
