# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-09-24 02:58
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20170921_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
