# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-09-25 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='one_time_token',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
