# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-09-25 18:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20170925_1742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='one_time_token',
        ),
        migrations.RemoveField(
            model_name='user',
            name='token',
        ),
    ]
